// Generated by scripts/build-migrations.ts from drizzle/. Do not edit by hand.
// Committed on purpose: a compiled binary has no drizzle/ folder to read, so
// the migrations have to live in the module graph. __tests__/core/cache/migrations-generated.test.ts
// fails if this drifts from drizzle/.

export interface IEmbeddedMigration {
  tag: string;
  hash: string;
  /** The journal entry's `when`, written to `__drizzle_migrations.created_at` exactly as drizzle writes it. */
  createdAt: number;
  sql: string[];
}

export const EMBEDDED_MIGRATIONS: IEmbeddedMigration[] = [
  {
    tag: "0000_initial",
    hash: "48a68ce0205d4fb23c30b5ef217a8c14a0088131af0463800b997d62b88f92f3",
    createdAt: 1785639211714,
    sql: [
      "CREATE TABLE `dialogs` (\n\t`peer_id` text PRIMARY KEY NOT NULL,\n\t`pinned` integer DEFAULT 0 NOT NULL,\n\t`unread_count` integer DEFAULT 0 NOT NULL,\n\t`unread_mentions` integer DEFAULT 0 NOT NULL,\n\t`read_inbox_max_id` integer DEFAULT 0 NOT NULL,\n\t`read_outbox_max_id` integer DEFAULT 0 NOT NULL,\n\t`top_message_id` integer,\n\t`last_message_at` integer,\n\t`muted_until` integer DEFAULT 0 NOT NULL,\n\t`folder_id` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`peer_id`) REFERENCES `peers`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `idx_dialogs_order` ON `dialogs` (`pinned`,`last_message_at`);",
      "\nCREATE TABLE `messages` (\n\t`peer_id` text NOT NULL,\n\t`id` integer NOT NULL,\n\t`from_id` text,\n\t`date` integer NOT NULL,\n\t`edit_date` integer,\n\t`text` text,\n\t`entities` text,\n\t`reply_to_msg_id` integer,\n\t`fwd_from` text,\n\t`media_kind` text,\n\t`media_json` text,\n\t`out` integer DEFAULT 0 NOT NULL,\n\t`deleted` integer DEFAULT 0 NOT NULL,\n\tPRIMARY KEY(`peer_id`, `id`),\n\tFOREIGN KEY (`peer_id`) REFERENCES `peers`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `idx_messages_peer_date` ON `messages` (`peer_id`,`date`);",
      "\nCREATE TABLE `peers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`type` text NOT NULL,\n\t`access_hash` text,\n\t`title` text NOT NULL,\n\t`username` text,\n\t`is_self` integer DEFAULT 0 NOT NULL,\n\t`is_bot` integer DEFAULT 0 NOT NULL,\n\t`status` text,\n\t`status_seen_at` integer,\n\t`updated_at` integer NOT NULL\n);\n",
      "\nCREATE TABLE `sync_state` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` integer NOT NULL\n);\n",
    ],
  },
];
