import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';

const STATEMENT_BREAKPOINT = '--> statement-breakpoint';

export interface IJournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

export interface IJournal {
  version: string;
  dialect: string;
  entries: IJournalEntry[];
}

export interface IReadMigration {
  tag: string;
  hash: string;
  createdAt: number;
  sql: string[];
}

export const MIGRATIONS_FOLDER = new URL('../drizzle', import.meta.url).pathname;
export const GENERATED_PATH = new URL('../src/core/cache/migrations.generated.ts', import.meta.url).pathname;

/**
 * The hash is `createHash('sha256').update(query).digest('hex')` over the whole
 * unmodified file, and the statements are `query.split('--> statement-breakpoint')`
 * with no trimming — both copied from `readMigrationFiles` in
 * `node_modules/drizzle-orm/migrator.js`. They must stay identical: a database
 * migrated by drizzle-kit records that hash in `__drizzle_migrations`, and a
 * hash computed any other way would make an already-migrated database look
 * untouched and re-run its migrations over live data.
 */
export const readMigrations = (opts: { migrationsFolder: string }): IReadMigration[] => {
  const journalPath = `${opts.migrationsFolder}/meta/_journal.json`;
  const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as IJournal;

  return journal.entries.map(entry => {
    const query = readFileSync(`${opts.migrationsFolder}/${entry.tag}.sql`, 'utf8');

    return {
      tag: entry.tag,
      hash: createHash('sha256').update(query).digest('hex'),
      createdAt: entry.when,
      // A trailing breakpoint would leave an empty chunk that SQLite rejects as
      // a statement; drizzle happens never to emit one, and dropping it here
      // costs nothing because an all-whitespace chunk executes nothing anyway.
      sql: query.split(STATEMENT_BREAKPOINT).filter(statement => statement.trim() !== ''),
    };
  });
};

export const buildMigrationsModuleSource = (opts: { migrationsFolder: string }): string => {
  const migrations = readMigrations({ migrationsFolder: opts.migrationsFolder });

  const entries = migrations
    .map(migration => {
      const statements = migration.sql.map(statement => `      ${JSON.stringify(statement)},`).join('\n');

      return [
        '  {',
        `    tag: ${JSON.stringify(migration.tag)},`,
        `    hash: ${JSON.stringify(migration.hash)},`,
        `    createdAt: ${migration.createdAt},`,
        '    sql: [',
        statements,
        '    ],',
        '  },',
      ].join('\n');
    })
    .join('\n');

  return [
    '// Generated by scripts/build-migrations.ts from drizzle/. Do not edit by hand.',
    '// Committed on purpose: a compiled binary has no drizzle/ folder to read, so',
    "// the migrations have to live in the module graph. __tests__/core/cache/migrations-generated.test.ts",
    '// fails if this drifts from drizzle/.',
    '',
    'export interface IEmbeddedMigration {',
    '  tag: string;',
    '  hash: string;',
    '  /** The journal entry\'s `when`, written to `__drizzle_migrations.created_at` exactly as drizzle writes it. */',
    '  createdAt: number;',
    '  sql: string[];',
    '}',
    '',
    'export const EMBEDDED_MIGRATIONS: IEmbeddedMigration[] = [',
    entries,
    '];',
    '',
  ].join('\n');
};

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, buildMigrationsModuleSource({ migrationsFolder: MIGRATIONS_FOLDER }));
  process.stdout.write(`Wrote ${GENERATED_PATH}\n`);
}
